### ISSUE TITLE
Document CrateKube development workflow

### ISSUE THREAD

**Issue by pdgrenon** [cratekube/cratekube#5]
### Problem to solve
CrateKube contributors will not be familiar with the way we work. If we expect all new components to go through a development pipeline of architecture -> code-level design -> automated tests -> implementation, we need to document our workflow.

### Proposal
To ensure that contributors have all of the information they need to build new features into CrateKube, we should document the way we work. This documentation needs to include an explanation for how we use all of the following stages of development:
- Proof of concepts
- Architecture pages
- Code-level designs
- Automated testing
- Implementation

Additionally, this documentation should lay out the expectations for the use of containers, CI/CD, and code reviews (or link to relevant sections of the contribution guidelines if that information already exists).

Since our open source repositories now have minimum code coverage checks, it may be necessary to change our development flow to accommodate. This will need to be part of the discussion for this issue, and documented appropriately. 

### Intended users
This will be useful for all contributors that want to build a new CrateKube component. 

### Further details
None.

### Permissions and Security
There are no security implications regarding this documentation. All of this information can be made public, as none of this information should be secret.

### Documentation
Documentation is the primary deliverable of this issue. There is no need for additional documentation.

### How can we measure success?
The measure of success is whether future contributors are able to understand the CrateKube development workflow for new components. 

### When is this feature complete?
This feature is complete when the tribal knowledge of CrateKube's  development workflow has been documented in a place accessible to the entire CrateKube community.

### Links / references
The architecture standards developed in #4 would a useful link to include in this documentation.

**Comment by kod4n** [comment]
Couple of notes, I'm not seeing an `Implementation` section in the list of stages for development.  Another key point with this flow is we may run into issues getting our tests to pass if we require a certain percentage of code coverage.  If we do code design/testing/impl in different stages then we will need to either ignore code coverage checks (not recommended) or find some other way to do this flow.

**Comment by pdgrenon** [comment]
I was thinking that the implementation is implied, and was trying to call out all of the things we do _before_ implementation, but being explicit is better. I'll add that.

Do we already have code coverage checks, or are you saying that we are going to run into issues implementing those in the future with this flow?

**Comment by kod4n** [comment]
We already have code coverage checks, if we fall below a given threshold builds will begin to fail.

**Comment by pdgrenon** [comment]
Ah, interesting. It sounds like we may need to change our flow a bit to account for that. Good call. That will need to be a part of the discussion. I will add a note to the issue.

**Comment by code4dc** [comment]
TODO: Make sure we specify that architecture and design will be done in the cratekube repo while testing and implementation will be done at each module's individual repo

**Comment by forktheweb** [comment]
For this document:  https://github.com/cratekube/cratekube/blob/master/CONTRIBUTING.md
Here's my feedback:
* It would be nice to have a sentence about if you are using intellij you can check the box for "sign-off commit"
* For PR rebasing, it would be nice if we said that this is because we require a single commit for all PRs (perhaps a link to a rebasing guide)
* For test cases it might be good to link to Spock and explain how we do TDD
* In the paragraph directly after those bullets, you have an "_" at the end, this should probably be removed.

For this document:  https://github.com/cratekube/cratekube/blob/master/docs/Development.md
Here's more feedback:
* Under "Architecture" there are no examples:     (Examples can be seen here ......).
* Perhaps link to the Architecture Guidelines for contributors
* Under code-level design, we could link to: cratekube/dropwizard-groovy-template
* For: " all microservices should have a relevant docker-compose.yaml file " .... aren't we moving towards k8s YAML?
* "This will ensure that the new components"... component needs an apostrophe
* We may want to link to Spock testing docs
* We could elaborate more on the CI/CD and Security sections in the future
Other than those suggestions, it LGTM. (edited) 


Aside from those suggestions, which we could always iterate on... it does look like you passed the acceptance criteria for a first iteration quite easily.

**Comment by code4dc** [comment]
Issue is closed with additional required changes described in https://github.com/cratekube/cratekube/issues/24
