### ISSUE TITLE
CrateKube initialization should support any AWS Region 

### ISSUE THREAD

**Issue by code4dc** [cratekube/cratekube#50]
### Summary

If a user attempts to run `cratekube init` and has the AWS_REGION environment variable set to anything except for "us-east-1" the initialization will fail. 

### Steps to reproduce

Set AWS_REGION to "us-west-1" and run `cratekube init`. After a while the code will error out, and the cratekube stack in Cloud Formation will have an Event with the following error: 
> The image id '[ami-09edd32d9b0990d49]' does not exist......

### What is the current *bug* behavior?

`cratekube init` errors out when AWS_REGION is not `us-east-1` 

### What is the expected *correct* behavior?

`cratekube init` should sucessfully create a cratekube stack in any AWS Region

### Relevant documentation

![image](https://user-images.githubusercontent.com/5297914/81609733-a07a4800-9395-11ea-9025-09ec3ba77a47.png)

### Possible fixes

AMI ids are tied to each region, so we'll need to get those based on the region and set them in `platform-cluster.yaml` before launching terraform.

**Comment by danielfoglio** [comment]
There is a new error, which is why this issue is remaining open. `Your requested instance type (t2.large) is not supported in your requested Availability Zone (us-west-2d). Please retry your request by not specifying an Availability Zone or choosing us-west-2a, us-west-2b, us-west-2c. (Service: AmazonEC2; Status Code: 400; Error Code: Unsupported; Request ID: 337686ce-d2cb-42ed-94a8-55e6c4bccfa9)
`

**Comment by danielfoglio** [comment]
I have been unable to reproduce the above error consistently. A new issue will be created if it persists.
